-- Los datos de demostración se insertan con PHP en init.php
-- (usuario demo@local.test / demo123, equipo personal y miembro owner).
-- Este archivo queda como referencia si prefieres sembrar a mano:
--
-- INSERT INTO teams (name, description) VALUES ('Mi espacio — Demo', 'Espacio de trabajo personal');
-- INSERT INTO users (email, display_name, password_hash, role, availability, personal_team_id)
-- VALUES ('demo@local.test', 'Usuario Demo', '<bcrypt de demo123>', 'admin', 'available', 1);
-- INSERT INTO team_members (team_id, user_id, role_in_team) VALUES (1, 1, 'owner');
